<a href="https://colab.research.google.com/github/HarshShetye/Djs_Compute_Task/blob/main/ML_Compute_Task_2__Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Harsh Shetye_60009210068

#### Import NumPy 

In [ ]:
import numpy as np

#### Create an array of 10 zeros 

In [ ]:
array=np.zeros(10)
print(f"Array of 10 zeros {array}")

Array of 10 zeros [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [ ]:
array=np.ones(10)
print(f"Array of 10 ones {array}")

Array of 10 ones [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [ ]:
array=np.ones(10)*5
print(f"Array of 10 fives {array}")

Array of 10 fives [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Create an array of the integers from 10 to 50 -!del!-

In [ ]:
array=np.arange(10,50)
print(f"Array of all the integers from 10 to 50 {array}")

Array of all the integers from 10 to 50 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### Create an array of all the even integers from 10 to 50  -!del!-

In [ ]:
array=np.arange(10,51,2)
print(f"Array of all the even integers from 10 to 50 {array}")

Array of all the even integers from 10 to 50 [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1  -!del!-

In [ ]:
import random
random.uniform(0,1)

0.8761319078947432

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
np.random.normal(size=25)

array([ 1.35175716, -0.31681167, -1.71341868, -0.41416775,  0.960195  ,
        0.20931876,  0.36321963, -0.68673162,  1.46800488, -0.37763658,
        1.55565991, -0.60517729,  0.36065796, -0.71931568, -0.39443169,
        0.2416938 ,  0.16661261, -0.8429883 ,  0.31404146, -0.55035876,
       -0.01101535, -2.76255724,  0.08821279,  0.75114679,  0.97828143])

In [ ]:
np.random.normal(0,1,25)

array([ 0.0634644 ,  0.91695249,  0.97724475, -0.86181394, -0.33094402,
        0.79519322,  0.83885608,  0.36791234, -0.296996  ,  1.08542608,
        1.40860641, -0.75115517, -0.27986855, -0.76530163, -0.57147316,
       -0.11608432, -0.96311663, -1.57161855, -0.12356364, -0.41967739,
       -0.32866962,  0.6795514 , -0.01356896,  0.07268175,  1.00091489])

#### Create the following matrix: -!del!-

In [ ]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1: 

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
m = np.arange(11,26)
m = np.delete(m, np.arange(0, m.size, 5)).reshape(3,4)
print(m)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
print(20)

20


In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
np.arange(2,13,5).reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
np.arange(21,26)

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
np.arange(16,26).reshape(2,5)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [ ]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [ ]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

#### Multiply two matrices using NumPy.

A = [[1, 2], [2, 3]]

B = [[4, 5], [6, 7]]

So, A.B = [[1*4 + 2*6, 2*4 + 3*6], [1*5 + 2*7, 2*5 + 3*7]

The computed answer will be: [[16, 26], [19, 31]]


In [ ]:
A = [[1,2], [2,3]]
B = [[4,5], [6,7]]
print(np.dot(A,B))

[[16 19]
 [26 31]]


####Replace NaN values with average of that column

Initial array :  

[[ 1.3  2.5  3.6  nan]
 [ 2.6  3.3  nan  5.5]
 [ 2.1  3.2  5.4  6.5]]


In [ ]:
initial_array = np.array([[1.3, 2.5, 3.6, np.nan],[2.6, 3.3, np.nan, 5.5],[2.1, 3.2, 5.4, 6.5]])
print(initial_array,"\n")

column_avg = np.nanmean(initial_array, axis = 0)
print (f"column_avg \n{column_avg}\n")

index = np.where(np.isnan(initial_array))
initial_array[index] = np.take(column_avg,index[1])

print (f"final array \n{initial_array}")

[[1.3 2.5 3.6 nan]
 [2.6 3.3 nan 5.5]
 [2.1 3.2 5.4 6.5]] 

column_avg 
[2.  3.  4.5 6. ]

final array 
[[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


# You're done!

Pandas

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv("/content/drive/MyDrive/ML_Mentee/data.csv")
df

Unnamed: 0  acousticness  danceability  duration_ms  energy  \
0              0       0.01020         0.833       204600   0.434   
1              1       0.19900         0.743       326933   0.359   
2              2       0.03440         0.838       185707   0.412   
3              3       0.60400         0.494       199413   0.338   
4              4       0.18000         0.678       392893   0.561   
...          ...           ...           ...          ...     ...   
2012        2012       0.00106         0.584       274404   0.932   
2013        2013       0.08770         0.894       182182   0.892   
2014        2014       0.00857         0.637       207200   0.935   
2015        2015       0.00164         0.557       185600   0.992   
2016        2016       0.00281         0.446       204520   0.915   

      instrumentalness  key  liveness  loudness  mode  speechiness    tempo  \
0             0.021900    2    0.1650    -8.795     1       0.4310  150.062   
1             0.006110    1    0.1370   -10.401     1       0.0794  160.083   
2             0.000234    2    0.1590    -7.148     1       0.2890   75.044   
3             0.510000    5    0.0922   -15.236     1       0.0261   86.468   
4             0.512000    5    0.4390   -11.648     0       0.0694  174.004   
...                ...  ...       ...       ...   ...          ...      ...   
2012          0.002690    1    0.1290    -3.501     1       0.3330   74.976   
2013          0.001670    1    0.0528    -2.663     1       0.1310  110.041   
2014          0.003990    0    0.2140    -2.467     1       0.1070  150.082   
2015          0.677000    1    0.0913    -2.735     1       0.1330  150.011   
2016          0.000039    9    0.2180    -6.221     1       0.1410  190.013   

      time_signature  valence  target                            song_title  \
0                4.0    0.286       1                              Mask Off   
1                4.0    0.588       1                               Redbone   
2                4.0    0.173       1                          Xanny Family   
3                4.0    0.230       1                        Master Of None   
4                4.0    0.904       1                        Parallel Lines   
...              ...      ...     ...                                   ...   
2012             4.0    0.211       0   Like A Bitch - Kill The Noise Remix   
2013             4.0    0.867       0                                 Candy   
2014             4.0    0.470       0  Habit - Dack Janiels & Wenzday Remix   
2015             4.0    0.623       0                         First Contact   
2016             4.0    0.402       0                    I Wanna Get Better   

                artist  
0               Future  
1     Childish Gambino  
2               Future  
3          Beach House  
4          Junior Boys  
...                ...  
2012    Kill The Noise  
2013    Dillon Francis  
2014          Rain Man  
2015        Twin Moons  
2016         Bleachers  

[2017 rows x 17 columns]

In [ ]:
#Find songs with value for energy column greater than 0.4 and display values for song_title column.
df_filt = df[df['energy'] > 0.4] 
df_filt2 = df_filt.sort_values('energy')[['song_title', 'artist','energy']]
df_filt2

song_title                    artist  energy
926                        No Woman                   Whitney   0.401
1811  Can't Blame a Girl for Trying         Sabrina Carpenter   0.401
22                        Imma Ride                Young Thug   0.401
41       I Don't Sell Molly No More             ILoveMakonnen   0.402
1971                Fog On the Tyne               Lindisfarne   0.403
...                             ...                       ...     ...
1332                Beautiful Agony          Within The Ruins   0.992
1347                     Unanswered           Suicide Silence   0.993
1297              A Darkened Gospel      A Wake in Providence   0.994
1322                     Pitchblack  Walking Dead On Broadway   0.997
1299                  No Absolution         Thy Art Is Murder   0.998

[1830 rows x 3 columns]

In [ ]:
#For songs with duration duration_ms value less than 300000 ms (300 s), find Top 10 “fastest” songs( songs with highest values for tempo column ) and display values for song_title, artistcolumns.
df_1 = df[df['duration_ms'] < 300000]
df_2 = df_1.sort_values('tempo')[['song_title', 'artist','duration_ms','tempo']].tail(10)
df_3 = df_2.sort_values('tempo', ascending=False)
df_3

song_title            artist  duration_ms    tempo
124       Danger and Dread        Brown Bird       226333  209.686
718            Hannah Hunt   Vampire Weekend       237973  207.969
1960            Puppy Love      Donny Osmond       184800  203.822
1711               Amazing     Big Time Rush       201720  202.013
809        Tupelo - Part 1       Pop Staples       174067  200.749
826     Living Every Dream            Antwon       293851  200.035
1339  The Shaping Sickness  Shadow of Intent       246689  199.988
102         Willing & Able        Disclosure       292760  199.727
1802             Mad Love.              JoJo       244413  199.519
532        Wake Bake Skate            FIDLAR        99413  198.040

In [ ]:
#Find songs with value for artist column = Drake and value for energy column greater than 0.5 and display values for song_title column.
df_a = df[(df['energy'] > 0.5) & (df['artist'] == 'Drake')]
df_b = df_a.sort_values('energy')[['song_title', 'artist', 'energy']]
df_b

song_title artist  energy
1223                Take Care  Drake   0.527
589   Started From the Bottom  Drake   0.531
37                    Jumpman  Drake   0.547
5                    Sneakin’  Drake   0.560
440                 Headlines  Drake   0.571
117             Hotline Bling  Drake   0.623
154                 Big Rings  Drake   0.676
779   0 To 100 / The Catch Up  Drake   0.709
1016         Skepta Interlude  Drake   0.822
1218          Best I Ever Had  Drake   0.861

In [ ]:
#Create a dataframe of the songs that rank among top 10 for the instrumentalness metric. This dataframe should only contain the instrumentalness, song title and artist columns.
df_i=df.sort_values('instrumentalness')[['instrumentalness', 'song_title', 'artist']].tail(10)
df_ii = df_i.sort_values('instrumentalness', ascending=False)
df_ii

instrumentalness                            song_title  \
1313             0.976                       Senseless Order   
271              0.968  So Destroyed (channeling Rage Peace)   
1575             0.964             A Hundred Dreams from Now   
1619             0.958                                 Raven   
725              0.957                     Strandbar (disko)   
1546             0.956                        Almas vaggvisa   
1322             0.955                            Pitchblack   
1661             0.954                               Yebisah   
1349             0.954                       Prismatic Abyss   
121              0.952                        Chasing Heaven   

                        artist  
1313        Signs of the Swarm  
271                Prince Rama  
1575                Ray Bryant  
1619             John Dahlbäck  
725                 Todd Terje  
1546         Jan Lundgren Trio  
1322  Walking Dead On Broadway  
1661               Mark Knight  
1349           Aversions Crown  
121                 Bassnectar

In [ ]:
#Create a dataframe of the average tempo for each of the top 10 most occurring artists.
dfx=df['artist'].value_counts().head(10)
dfx

Drake              16
Rick Ross          13
Disclosure         12
WALK THE MOON      10
Backstreet Boys    10
Crystal Castles     9
FIDLAR              9
Future              8
Fall Out Boy        8
Skrillex            8
Name: artist, dtype: int64

In [ ]:
dfy0=df['artist'].value_counts().index.tolist()[:10]
dfy=df.loc[df['artist'].isin(dfy0)]
dfy

Unnamed: 0  acousticness  danceability  duration_ms  energy  \
0              0      0.010200         0.833       204600   0.434   
2              2      0.034400         0.838       185707   0.412   
5              5      0.004790         0.804       251333   0.560   
6              6      0.014500         0.739       241400   0.472   
15            15      0.019000         0.637       188333   0.832   
...          ...           ...           ...          ...     ...   
1990        1990      0.000590         0.594       218720   0.858   
1991        1991      0.000366         0.544       245133   0.788   
1992        1992      0.007490         0.446       241253   0.881   
1993        1993      0.001900         0.551       195280   0.732   
1994        1994      0.510000         0.630       240000   0.772   

      instrumentalness  key  liveness  loudness  mode  speechiness    tempo  \
0             0.021900    2    0.1650    -8.795     1       0.4310  150.062   
2             0.000234    2    0.1590    -7.148     1       0.2890   75.044   
5             0.000000    8    0.1640    -6.682     1       0.1850   85.023   
6             0.000007    1    0.2070   -11.204     1       0.1560   80.030   
15            0.056300    6    0.3160    -6.637     1       0.1630   99.988   
...                ...  ...       ...       ...   ...          ...      ...   
1990          0.000003    9    0.0642    -4.339     1       0.0387  138.021   
1991          0.000000    5    0.1410    -5.593     0       0.0474  148.121   
1992          0.000000    2    0.1300    -4.368     1       0.0545  169.889   
1993          0.000000    9    0.0764    -6.081     1       0.0627  145.107   
1994          0.000023    1    0.0881    -6.986     1       0.0297   99.964   

      time_signature  valence  target    song_title           artist  
0                4.0    0.286       1      Mask Off           Future  
2                4.0    0.173       1  Xanny Family           Future  
5                4.0    0.264       1      Sneakin’            Drake  
6                4.0    0.308       1   Childs Play            Drake  
15               4.0    0.317       1          Char  Crystal Castles  
...              ...      ...     ...           ...              ...  
1990             4.0    0.646       0     Avalanche    WALK THE MOON  
1991             4.0    0.821       0         Jenny    WALK THE MOON  
1992             4.0    0.428       0      Portugal    WALK THE MOON  
1993             4.0    0.628       0    Quesadilla    WALK THE MOON  
1994             4.0    0.714       0       Aquaman    WALK THE MOON  

[103 rows x 17 columns]

In [ ]:
dfz=dfy.groupby('artist').mean()
dfz1=dfz[['tempo']]
dfz1

tempo
artist                     
Backstreet Boys  113.066600
Crystal Castles  128.600778
Disclosure       128.118417
Drake            112.406750
FIDLAR           145.983444
Fall Out Boy     133.815625
Future           128.989625
Rick Ross        110.721923
Skrillex         132.454125
WALK THE MOON    136.163600